### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by homileak** [pcrbot/hiumsentences#1]
按照安装说明clone仓库，然后将相应的资源放到了res的正确位置
出发关键字后提示
[2021-06-25 17:45:44,289 nonebot] INFO: Self: 1816900000, Message 33500000 from 25000000@[群:796500000]: '到点了'
[2021-06-25 17:45:44,290 hiumsentences] INFO: Message 33500000 triggered net_ease_cloud_word.
[2021-06-25 17:45:44,291 hiumsentences] ERROR: <class 'NotImplementedError'> occured when net_ease_cloud_word handling message 33500000.
[2021-06-25 17:45:44,291 hiumsentences] ERROR: 
Traceback (most recent call last):
  File "/root/pcrbot/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/pcrbot/HoshinoBot/hoshino/modules/hiumsentences/hiumsentences.py", line 57, in net_ease_cloud_word
    sentences += nt_word
  File "/root/.cache/pypoetry/virtualenvs/pcrbot-k97M30qc-py3.9/lib/python3.9/site-packages/aiocqhttp/message.py", line 137, in __iadd__
    raise NotImplementedError
NotImplementedError
[2021-06-25 17:45:44,291 nonebot] INFO: Message 33500000 is ignored: Handled by Hoshino

**Comment by homileak** [comment]
将“hiumsentences.py”最后三行修改成如下后正常了。
nt_word = get_nt_words()
msg = sentences + nt_word
await bot.send(ev, msg)

**Comment by Zoe-Wh1t3zZ** [comment]
> nt_word = get_nt_words()
> msg = sentences + nt_word
> await bot.send(ev, msg)

谢谢，正常发图片了
